name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lefthook:
    runs-on: ubuntu-latest
    env:
      HOME: /home/runner
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@311740298599dab21f2dc0f83f1d8c974215d197
        with:
          skip-build: "true"
          keep-home: "true"
          flake-check-timeout: "600"
          flake-eval-timeout: "600"

  build-linux:
    runs-on: ubuntu-latest
    env:
      HOME: /home/runner
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@311740298599dab21f2dc0f83f1d8c974215d197
        with:
          skip-lefthook: "true"
          keep-home: "true"

  build-darwin:
    runs-on: macos-latest
    env:
      HOME: /Users/runner
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@311740298599dab21f2dc0f83f1d8c974215d197
        with:
          skip-lefthook: "true"
          keep-home: "true"

  build-linux-arm:
    runs-on: ubuntu-latest
    env:
      HOME: /home/runner
    steps:
      - uses: pr0d1r2/nix-lefthook-ci-action@311740298599dab21f2dc0f83f1d8c974215d197
        with:
          skip-lefthook: "true"
          extra-platforms: aarch64-linux
          keep-home: "true"
